import type {Metadata} from "next";
import {Poppins} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";

const poppins = Poppins({weight: ["400", "500", "600"], subsets: ["latin"], variable: "--font-sans"});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={cn(
            "m-6 min-h-screen bg-background font-sans",
            poppins.variable
        )}>{children}</body>
        </html>
    );
}
